// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRhA0YDy_NLcXs5gb5dsXbRNgjxr6Vze0',
    appId: '1:429606720055:web:81b8f234903564508be5b2',
    messagingSenderId: '429606720055',
    projectId: 'stackednotesapp',
    authDomain: 'stackednotesapp.firebaseapp.com',
    storageBucket: 'stackednotesapp.firebasestorage.app',
    measurementId: 'G-644NSVJ61F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4bMjDTpuQtwVruEoUKWIvRfTHEFriAc',
    appId: '1:429606720055:android:5d9265a691ac934d8be5b2',
    messagingSenderId: '429606720055',
    projectId: 'stackednotesapp',
    storageBucket: 'stackednotesapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI1to8DHwMedQpR-_UmLVUg_Hw1EKZCx0',
    appId: '1:429606720055:ios:2582dc47f291f5038be5b2',
    messagingSenderId: '429606720055',
    projectId: 'stackednotesapp',
    storageBucket: 'stackednotesapp.firebasestorage.app',
    iosBundleId: 'com.example.myStackedNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI1to8DHwMedQpR-_UmLVUg_Hw1EKZCx0',
    appId: '1:429606720055:ios:2582dc47f291f5038be5b2',
    messagingSenderId: '429606720055',
    projectId: 'stackednotesapp',
    storageBucket: 'stackednotesapp.firebasestorage.app',
    iosBundleId: 'com.example.myStackedNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRhA0YDy_NLcXs5gb5dsXbRNgjxr6Vze0',
    appId: '1:429606720055:web:53bc0873359361948be5b2',
    messagingSenderId: '429606720055',
    projectId: 'stackednotesapp',
    authDomain: 'stackednotesapp.firebaseapp.com',
    storageBucket: 'stackednotesapp.firebasestorage.app',
    measurementId: 'G-5HFJT5X3LD',
  );
}
